### ISSUE TITLE
Add Icones do instagram,   Youtube e tbm do linkedin

### ISSUE THREAD

**Issue by pachicodes** [feministech/maratona3#4]

**Comment by pachicodes** [comment]
1. Pegar no Font Awesome as imagens dos seguintes icons: a-instagram(nome rede-instagram.png), b-Youtube (nome rede-youtube.png) e c-linkedin
2.  Adicionar o do Youtube pra Julia Labs
3. Adicionar do insta pra 
Os links e legendas jah estao prontos, soh falta colocar as imagens na pasta de iamgens

LinkedIn pode ser adicionado para todas que quiserem

**Comment by pfanovaes** [comment]
insta: <i class="fab fa-instagram"></i>
youtube: <i class="fab fa-youtube"></i>
linkedin: <i class="fab fa-linkedin"></i>

**Comment by pfanovaes** [comment]
linkedin: `<i class="fab fa-linkedin"></i>`
insta: `<i class="fab fa-instagram"></i>`
youtube: `<i class="fab fa-youtube"></i>`
